name: prek
title: prek
base: core26
version: 0.4.4
summary: A fast Git hook manager written in Rust.
description: |
  A fast Git hook manager written in Rust, designed as a drop-in
  alternative to pre-commit, reimagined.

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
  riscv64:

parts:
  prek:
    plugin: rust
    source: https://github.com/j178/prek.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-attributes:
      - enable-patchelf
    organize:
      prek: bin/prek
      lib*.so: lib/

apps:
  prek:
    command: bin/prek
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
